mixin.bugfix.extra_experimental_screen=false
mixin.bugfix.world_screen_skipped=false
mixin.feature.branding=false
mixin.feature.integrated_server_watchdog=false
mixin.feature.mcfunction_profiling=false
mixin.feature.measure_time=false
mixin.feature.snapshot_easter_egg=false
mixin.perf.dynamic_entity_renderers=true
mixin.perf.dynamic_resources=true